# Generated by Django 4.2.18 on 2025-01-28 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_parameters_default_parameter_set'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParameterSetWall',
        ),
    ]
