# Generated by Django 4.2.18 on 2025-01-28 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_delete_parametersetwall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametersetground',
            name='parameter_set',
        ),
        migrations.DeleteModel(
            name='ParameterSetBarrier',
        ),
        migrations.DeleteModel(
            name='ParameterSetGround',
        ),
    ]
