# Generated by Django 4.2.18 on 2025-01-28 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_remove_parametersetground_parameter_set_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterset',
            name='token_cents_value',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='tokens_per_period',
        ),
    ]
