# Generated by Django 4.2.18 on 2025-01-28 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_remove_parameterset_token_cents_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterset',
            name='avatar_animation_speed',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='avatar_bound_box_percent',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='avatar_move_speed',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='avatar_scale',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='cool_down_length',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='interaction_length',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='interaction_range',
        ),
    ]
