# Generated by Django 4.2.18 on 2025-01-29 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_parametersettreatment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersettreatment',
            name='parameter_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_treatments', to='main.parameterset'),
        ),
    ]
