# Generated by Django 4.2.18 on 2025-01-30 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_alter_parametersettreatment_parameter_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersettreatment',
            name='id_label',
            field=models.CharField(default='Name Here', max_length=2, verbose_name='ID Label'),
        ),
    ]
