# Generated by Django 4.2.18 on 2025-01-30 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_alter_parametersettreatment_id_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametersettreatment',
            name='id_label',
        ),
        migrations.AddField(
            model_name='parametersettreatment',
            name='id_label_pst',
            field=models.CharField(default='Name Here', max_length=30, verbose_name='ID Label'),
        ),
    ]
