# Generated by Django 4.2.18 on 2025-01-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0077_remove_parametersettreatment_id_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersettreatment',
            name='left_x',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Left Vertex X'),
        ),
        migrations.AlterField(
            model_name='parametersettreatment',
            name='left_y',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Left Vertex Y'),
        ),
        migrations.AlterField(
            model_name='parametersettreatment',
            name='middle_x',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name='Middle Vertex X'),
        ),
        migrations.AlterField(
            model_name='parametersettreatment',
            name='middle_y',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=4, verbose_name='Middle Vertex Y'),
        ),
        migrations.AlterField(
            model_name='parametersettreatment',
            name='range_height',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=4, verbose_name='Range Height'),
        ),
        migrations.AlterField(
            model_name='parametersettreatment',
            name='range_width',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=4, verbose_name='Range Width'),
        ),
        migrations.AlterField(
            model_name='parametersettreatment',
            name='right_x',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Right Vertex X'),
        ),
        migrations.AlterField(
            model_name='parametersettreatment',
            name='right_y',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=4, verbose_name='Right Vertex Y'),
        ),
    ]
