# Generated by Django 4.2.18 on 2025-01-30 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0078_alter_parametersettreatment_left_x_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterSetPeriodblock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.IntegerField(default=1, verbose_name='Period Start')),
                ('period_end', models.IntegerField(default=1, verbose_name='Period End')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parameter_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_periodblocks_a', to='main.parameterset')),
                ('parameter_set_treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parameter_set_periodblocks_b', to='main.parametersettreatment')),
            ],
            options={
                'verbose_name': 'Parameter Set Periodblock',
                'verbose_name_plural': 'Parameter Set Periodblocks',
                'ordering': ['period_start'],
            },
        ),
    ]
