# Generated by Django 4.2.18 on 2025-01-30 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0079_parametersetperiodblock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametersettreatment',
            options={'verbose_name': 'Parameter Set Treatment', 'verbose_name_plural': 'Parameter Set Treatments'},
        ),
    ]
