# Generated by Django 4.2.18 on 2025-01-30 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0080_alter_parametersettreatment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterSetPlayerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.IntegerField(default=1, verbose_name='Group Number')),
                ('position', models.IntegerField(default=1, verbose_name='Position')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parameter_set_period_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_player_groups_b', to='main.parametersetperiodblock')),
                ('parameter_set_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_player_groups_a', to='main.parametersetplayer')),
            ],
            options={
                'verbose_name': 'Parameter Set Player Group',
                'verbose_name_plural': 'Parameter Set Player Groups',
                'ordering': ['parameter_set_period_block__period_start'],
            },
        ),
    ]
