# Generated by Django 4.2.18 on 2025-01-31 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_parametersetplayergroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametersettreatment',
            options={'ordering': ['id_label_pst'], 'verbose_name': 'Parameter Set Treatment', 'verbose_name_plural': 'Parameter Set Treatments'},
        ),
        migrations.RemoveField(
            model_name='parametersetplayer',
            name='parameter_set_group',
        ),
        migrations.DeleteModel(
            name='ParameterSetGroup',
        ),
    ]
