# Generated by Django 4.2.18 on 2025-02-04 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0082_alter_parametersettreatment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersettreatment',
            name='range_height_ticks',
            field=models.IntegerField(default=10, verbose_name='Range Height Ticks'),
        ),
        migrations.DeleteModel(
            name='ParameterSetNotice',
        ),
    ]
