# Generated by Django 4.2.18 on 2025-02-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0083_parametersettreatment_range_height_ticks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersettreatment',
            name='values',
            field=models.CharField(default='10,9,8,7,6,5,4,3,2,1', max_length=250, verbose_name='Values'),
        ),
    ]
