# Generated by Django 4.2.18 on 2025-02-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0084_parametersettreatment_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersettreatment',
            name='range_height',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5, verbose_name='Range Height'),
        ),
        migrations.AlterField(
            model_name='parametersettreatment',
            name='range_width',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5, verbose_name='Range Width'),
        ),
        migrations.AlterField(
            model_name='parametersettreatment',
            name='values',
            field=models.CharField(default='10,9,8,7,6,5,4,3,2,1', max_length=1000, verbose_name='Values'),
        ),
    ]
