# Generated by Django 4.2.18 on 2025-02-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0085_alter_parametersettreatment_range_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersetplayer',
            name='id_label',
            field=models.CharField(default='1', max_length=20, verbose_name='ID Label'),
        ),
    ]
