# Generated by Django 4.2.18 on 2025-02-13 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0089_remove_parameterset_period_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterset',
            name='break_frequency',
        ),
    ]
