# Generated by Django 4.2.18 on 2025-02-15 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0091_remove_parameterset_break_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametersettreatment',
            name='left_x',
        ),
        migrations.RemoveField(
            model_name='parametersettreatment',
            name='left_y',
        ),
        migrations.RemoveField(
            model_name='parametersettreatment',
            name='middle_x',
        ),
        migrations.RemoveField(
            model_name='parametersettreatment',
            name='middle_y',
        ),
        migrations.RemoveField(
            model_name='parametersettreatment',
            name='right_x',
        ),
        migrations.RemoveField(
            model_name='parametersettreatment',
            name='right_y',
        ),
    ]
