# Generated by Django 4.2.18 on 2025-02-15 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0092_remove_parametersettreatment_left_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersettreatment',
            name='scale_height',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5, verbose_name='Scale Height'),
        ),
        migrations.AddField(
            model_name='parametersettreatment',
            name='scale_width',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5, verbose_name='Scale Width'),
        ),
    ]
