# Generated by Django 4.2.18 on 2025-02-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0093_parametersettreatment_scale_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetplayergroup',
            name='start_box',
            field=models.IntegerField(default=0, verbose_name='Start Box'),
        ),
    ]
