# Generated by Django 4.2.18 on 2025-02-18 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0094_parametersetplayergroup_start_box'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterset',
            name='world_height',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='world_width',
        ),
        migrations.AddField(
            model_name='parameterset',
            name='enable_chat',
            field=models.BooleanField(default=False, verbose_name='Enable Chat'),
        ),
    ]
