# Generated by Django 4.2.18 on 2025-02-18 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0095_remove_parameterset_world_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterset',
            name='enable_chat',
            field=models.BooleanField(default=True, verbose_name='Enable Chat'),
        ),
    ]
