# Generated by Django 4.2.18 on 2025-02-20 23:58

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0096_alter_parameterset_enable_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplayer',
            name='chat_display_history',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Chat History'),
        ),
    ]
