# Generated by Django 4.2.18 on 2025-02-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0097_sessionplayer_chat_display_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionperiod',
            name='round_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
