# Generated by Django 4.2.18 on 2025-02-28 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0098_sessionperiod_round_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersettreatment',
            name='preserve_order',
            field=models.BooleanField(default=False, verbose_name='Preserve Order'),
        ),
    ]
