# Generated by Django 4.2.18 on 2025-03-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0099_parametersettreatment_preserve_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionevent',
            options={'ordering': ['period_number', 'group_number'], 'verbose_name': 'Session Event', 'verbose_name_plural': 'Session Events'},
        ),
        migrations.RemoveField(
            model_name='sessionevent',
            name='time_remaining',
        ),
        migrations.AddField(
            model_name='sessionevent',
            name='group_number',
            field=models.IntegerField(default=0, verbose_name='Group Number'),
        ),
    ]
