# Generated by Django 4.2.18 on 2025-03-05 18:25

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0100_alter_sessionevent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='period_block_data',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Period Block Data'),
        ),
    ]
