# Generated by Django 4.2.18 on 2025-03-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0101_session_period_block_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersettreatment',
            name='enable_chat',
            field=models.BooleanField(default=True, verbose_name='Enable Chat'),
        ),
        migrations.AddField(
            model_name='parametersettreatment',
            name='enable_transfer_cents',
            field=models.BooleanField(default=True, verbose_name='Enable Transfer Cents'),
        ),
    ]
