# Generated by Django 4.2.18 on 2025-03-06 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0102_parametersettreatment_enable_chat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterset',
            name='enable_chat',
        ),
    ]
