# Generated by Django 4.2.18 on 2025-03-06 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0104_remove_parametersettreatment_scale_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetperiodblock',
            name='help_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_notices', to='main.helpdocssubject'),
        ),
    ]
