# Generated by Django 4.2.18 on 2025-03-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0105_parametersetperiodblock_help_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructionset',
            name='p1_example_end_range',
            field=models.IntegerField(default=1, verbose_name='Person 1 Example End Range'),
        ),
        migrations.AddField(
            model_name='instructionset',
            name='p1_example_start_range',
            field=models.IntegerField(default=1, verbose_name='Person 1 Example Start Range'),
        ),
        migrations.AddField(
            model_name='instructionset',
            name='p2_example_end_range',
            field=models.IntegerField(default=20, verbose_name='Person 2 Example End Range'),
        ),
        migrations.AddField(
            model_name='instructionset',
            name='p2_example_start_range',
            field=models.IntegerField(default=11, verbose_name='Person 2 Example Start Range'),
        ),
        migrations.AddField(
            model_name='instructionset',
            name='p3_example_end_range',
            field=models.IntegerField(default=30, verbose_name='Person 3 Example End Range'),
        ),
        migrations.AddField(
            model_name='instructionset',
            name='p3_example_start_range',
            field=models.IntegerField(default=21, verbose_name='Person 3 Example Start Range'),
        ),
        migrations.AddField(
            model_name='instructionset',
            name='p4_example_end_range',
            field=models.IntegerField(default=40, verbose_name='Person 4 Example End Range'),
        ),
        migrations.AddField(
            model_name='instructionset',
            name='p4_example_start_range',
            field=models.IntegerField(default=31, verbose_name='Person 4 Example Start Range'),
        ),
    ]
