# Generated by Django 4.2.18 on 2025-03-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0106_instructionset_p1_example_end_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersettreatment',
            name='enable_transfer_cents',
            field=models.BooleanField(default=True, verbose_name='Enable Profit Transfer'),
        ),
    ]
