# Generated by Django 4.2.18 on 2025-03-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0107_alter_parametersettreatment_enable_transfer_cents'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersettreatment',
            name='enable_contest',
            field=models.BooleanField(default=True, verbose_name='Enable Contest'),
        ),
        migrations.AddField(
            model_name='parametersettreatment',
            name='enable_ready_button',
            field=models.BooleanField(default=True, verbose_name='Enable Ready Button'),
        ),
    ]
