# Generated by Django 4.2.18 on 2025-03-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0109_alter_parametersettreatment_range_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersettreatment',
            name='range_height',
            field=models.DecimalField(decimal_places=4, default=2, max_digits=7, verbose_name='Range Height'),
        ),
        migrations.AlterField(
            model_name='parametersettreatment',
            name='range_width',
            field=models.DecimalField(decimal_places=4, default=2, max_digits=7, verbose_name='Range Width'),
        ),
        migrations.AlterField(
            model_name='parametersettreatment',
            name='scale_width',
            field=models.DecimalField(decimal_places=4, default=2, max_digits=7, verbose_name='Scale Width'),
        ),
    ]
