# Generated by Django 4.2.18 on 2025-03-25 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0112_parametersettreatment_scale_height'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametersettreatment',
            old_name='range_height_ticks',
            new_name='scale_height_ticks',
        ),
    ]
