# Generated by Django 4.2.18 on 2025-03-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0113_rename_range_height_ticks_parametersettreatment_scale_height_ticks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersettreatment',
            name='scale_height_ticks',
            field=models.IntegerField(default=10, verbose_name='Scale Height Ticks'),
        ),
        migrations.AlterField(
            model_name='parametersettreatment',
            name='values',
            field=models.CharField(default='10,9,8,7,6,5,4,3,2,1', max_length=5000, verbose_name='Values'),
        ),
    ]
