# Generated by Django 4.2.18 on 2025-03-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0114_alter_parametersettreatment_scale_height_ticks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersettreatment',
            name='cost_percent',
            field=models.DecimalField(decimal_places=4, default=2, max_digits=7, verbose_name='Scale Width'),
        ),
    ]
