# Generated by Django 4.2.18 on 2025-03-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0116_alter_parametersettreatment_cost_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersettreatment',
            name='cost_area',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Cost Area'),
        ),
        migrations.AddField(
            model_name='parametersettreatment',
            name='revenue_area',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Revenue Area'),
        ),
    ]
