# Generated by Django 4.2.18 on 2025-03-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0117_parametersettreatment_cost_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersettreatment',
            name='inheritance',
            field=models.CharField(choices=[('Preset', 'Preset'), ('Copy', 'Copy'), ('Midpoint', 'Midpoint')], default='Preset', max_length=30, verbose_name='Inheritance'),
        ),
    ]
