# Generated by Django 4.2.18 on 2025-03-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0118_parametersettreatment_inheritance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametersettreatment',
            name='inheritance',
        ),
        migrations.AddField(
            model_name='parametersetperiodblock',
            name='inheritance',
            field=models.CharField(choices=[('Preset', 'Preset'), ('Copy', 'Copy'), ('Midpoint', 'Midpoint')], default='Preset', max_length=30, verbose_name='Inheritance'),
        ),
    ]
