# Generated by Django 4.2.18 on 2025-03-31 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0120_parameterset_inheritance_window'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersettreatment',
            name='id_label_pst',
            field=models.CharField(default='Name Here', max_length=100, verbose_name='ID Label'),
        ),
    ]
