# Generated by Django 4.2.18 on 2025-04-01 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0121_alter_parametersettreatment_id_label_pst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametersetplayer',
            name='start_x',
        ),
        migrations.RemoveField(
            model_name='parametersetplayer',
            name='start_y',
        ),
    ]
