# Generated by Django 4.2.18 on 2025-04-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0122_remove_parametersetplayer_start_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='show_waste',
            field=models.BooleanField(default=False, verbose_name='Show Waste'),
        ),
    ]
