# Generated by Django 4.2.18 on 2025-05-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0123_parameterset_show_waste'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='summary_type',
            field=models.CharField(choices=[('Partial', 'Partial'), ('Full', 'Full')], default='Full', max_length=10, verbose_name='Summary Type'),
        ),
        migrations.AlterField(
            model_name='parametersettreatment',
            name='enable_transfer_cents',
            field=models.BooleanField(default=True, verbose_name='Enable Money Transfer'),
        ),
    ]
