# Generated by Django 5.2.1 on 2025-09-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0124_parameterset_summary_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='Exchange Rate'),
        ),
    ]
